name: Nx Affected CI
on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: git fetch origin main
  
      - run: npm install

      - name: Lint Affected
        shell: bash
        run: npm run affected:lint -- --base=remotes/origin/main

      - name: Build Affected
        shell: bash
        run: npm run affected:build -- --base=remotes/origin/main

      - name: Test Affected
        shell: bash
        run: npm run affected:test -- --base=remotes/origin/main

      - name: Test Affected E2E
        shell: bash
        run: npm run affected:e2e -- --base=remotes/origin/main